/**:
    ros__parameters:
      message_type: "odometry"
      odometry_topic: "/Odometry"
      extrinsic_translation: [0.0, 0.0, 0.0]
      extrinsic_rotation_matrix: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
